## tensor기초

In [22]:
# 텐서 생성  
import torch
import numpy as np
x = torch.empty(5,4) # 빈 (5,4)텐서
x2 = torch.ones(3,3) # 1인 (3,3)텐서
x3 = torch.zeros(3,3) # 0인 (3,3)텐서
x4 = torch.rand(4,3) # 랜덤 (4,3)생성

x5 = [1,2,3]
x6 = np.array(([4,52,5],[1,2,3]))
x5 = torch.tensor(x5) # tensor로 변환
x6 = torch.tensor(x6) # tensor로 변환 

x7 = x6.numpy() # 다시 numpy배열로 변환
print(x5.size() , x6.size() , x7.shape)

torch.Size([3]) torch.Size([2, 3]) (2, 3)


In [16]:
# 텐서 연산 
x = torch.rand(2,2)
y = torch.rand(2,2)
print(torch.add(x,y))
print(y.add(x))

tensor([[0.9930, 1.2576],
        [1.3750, 1.0141]])
tensor([[0.9930, 1.2576],
        [1.3750, 1.0141]])


In [19]:
# 텐서 크기 변환
x = torch.rand(8,8) #64
print(x.size())
xx = x.view(-1,4,4) # 4,4,4
print(xx.size())
xxx = x.view(64)
print(xxx.size()) 

torch.Size([8, 8])
torch.Size([4, 4, 4])
torch.Size([64])


In [45]:
# 역전파 (간단한 합성함수 형태)
x = torch.ones(2,2,requires_grad=True)
y = x+1
z = 2*y**2 
r = z.mean() # z=2(x+1)^2
print(x)
print(y)
print(z)
print('---------------------'*3)
print('r : ',r)

r.backward() # r기준으로 역전파 dr/dx 계산 
print(x.grad) # 미분값 

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
---------------------------------------------------------------
r :  tensor(8., grad_fn=<MeanBackward0>)
tensor([[2., 2.],
        [2., 2.]])


In [77]:
from matplotlib import pyplot as plt
x= torch.FloatTensor(range(5)).unsqueeze(1) # 2차원으로 표현하기 위해 unsqueeze(1) = 첫번쨰 위치의 차원을 늘려준다
print(x.size())
print(x)
y = 2*x + torch.rand(5,1)
print(y)

torch.Size([5, 1])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[8.5793e-03],
        [2.5438e+00],
        [4.6226e+00],
        [6.3733e+00],
        [8.7303e+00]])


In [70]:
torch.rand(5,1)

tensor([[0.3483],
        [0.2034],
        [0.7841],
        [0.0478],
        [0.2033]])