##

## shape 관련

In [11]:
# shape
import numpy as np
a = np.zeros((2,3))
print(a.reshape(1,6)) # 1,6 
print(a.reshape(3,-1)) # 3,2
print(a.ravel()) # 1차원으로 1,6

b= np.array([[1,3],[0,-1]])
c= np.random.randint(0,10,4).reshape(2,-1)
np.matmul(b,c) # 행렬 연산
np.concatenate([b,c],axis=0).shape # aixs=0 아래로 붙는다


[[0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0.]


(4, 2)

## class관련

In [38]:
class DataPreprocessing:
    def __init__(self,data,target): # self넣어주고 원하는 변수가져오고 정의 
        self.data = data # 외부 데이터 
        self.target = target # 외부 데이터 
        self.num_instances = self.data.shape[0] 
        self.num_features = self.data.shape[1]
        
    def minmax(self): # 반드시 self기입 
        for i in range(self.num_instances):
            col = self.data[:,i]
            self.data[:,i] =(self.data[:,i]-np.min(col))/(np.max(col)-np.min(col))
        return self
    
    def normalization(self): # 반드시 self기입
        for i in range(self.num_features):
            col = self.data[:,i]
            mu , sigma = np.mean(col),np.std(col)
            self.data[:,i] = (self.data[:,i]-mu)/sigma
        return self
    
    def scaler(self,scaling=None): # 반드시 self 기입하고 입력값에 따라 위에 정의한 함수 기능 수행 
        if scaling == 'minmax':
            self.minmax()
            
        elif scaling == 'normalization':
            self.normalization()
    
        else:
            pass
        return self.data

In [49]:
data = np.random.normal(0,10,(5,5))
print(data)
print('-----------'*10)
target = np.random.normal(0,1,5)

data_process = DataPreprocessing(data,target)
data1 = data_process.scaler('asda')
print(data1)
print('-----------'*10)

data2 = data_process.scaler('minmax')
print(data2)
print('-----------'*10)

[[ -0.43126604   7.65108455   2.52802669   0.62216847   4.7712651 ]
 [ 16.23145433  14.67427148   5.0307811   -6.58236022  19.63745346]
 [  2.94726448  -9.62107198  17.14513426   6.06581845   9.82757329]
 [ -1.77140459   0.13326038 -11.66911401  15.7807664    3.07993813]
 [ -7.34652502  15.72887912  -6.93164727   1.40150587   6.38190797]]
--------------------------------------------------------------------------------------------------------------
[[ -0.43126604   7.65108455   2.52802669   0.62216847   4.7712651 ]
 [ 16.23145433  14.67427148   5.0307811   -6.58236022  19.63745346]
 [  2.94726448  -9.62107198  17.14513426   6.06581845   9.82757329]
 [ -1.77140459   0.13326038 -11.66911401  15.7807664    3.07993813]
 [ -7.34652502  15.72887912  -6.93164727   1.40150587   6.38190797]]
--------------------------------------------------------------------------------------------------------------
[[0.29329311 0.68134871 0.49271251 0.32216107 0.1021486 ]
 [1.         0.95839804 0.57957074 0. 

In [54]:
class Datapipeline(DataPreprocessing):
    def __init__(self, data):
        super().__init__(data, None)  # DataPreprocessing의 __init__ 메서드 호출(오버라이팅 )
        self.num_features = self.data.shape[1]
'''
오버라이딩(Overriding)은 하위 클래스가(DataPreprocessing)
상위 클래스(Datapipeline)에 이미 정의된 메서드에 대해 특정한 구현을 제공하는 개념
'''
data = np.random.normal(0, 10, (5, 5))
pipe = Datapipeline(data)
data = pipe.scaler('minmax')
print(data)


[[0.54240938 0.         0.20178463 0.44099768 0.        ]
 [0.         0.87340901 0.03694365 0.4161334  0.33524729]
 [0.34955012 0.47147533 0.04935694 0.         1.        ]
 [1.         0.2606112  0.         1.         0.22503933]
 [0.50325665 1.         1.         0.46786611 0.40479197]]
