In [1]:
import torch
import matplotlib.pyplot as plt
a = torch.ones(3) # 크기가 3인 1차원 텐서
print(a)
print(a.shape)

tensor([1., 1., 1.])
torch.Size([3])


In [9]:
points = torch.tensor([[4.0, 1.0 ,3], [5.0, 3.0,3], [2.0, 1.0,3]])
print(points)
print(points.shape) 
print(points[0,1])                                                                                                                         

tensor([[4., 1., 3.],
        [5., 3., 3.],
        [2., 1., 3.]])
torch.Size([3, 3])
tensor(1.)


In [2]:
image = torch.randn(3,5,6) # 3채널(색) , 5행 , 6열
image

tensor([[[ 0.6564, -0.1004,  0.8934, -0.8658, -1.9889,  0.4015],
         [-1.9737, -1.4124, -0.6331, -2.1054,  1.9837,  1.1340],
         [-0.8314, -0.8371, -0.1372,  0.7425, -0.0729,  0.0780],
         [-0.1954, -0.1095,  0.5222,  1.5207, -1.5092, -0.5382],
         [ 0.0431,  0.4880,  0.6099,  1.2415,  1.1515, -0.2428]],

        [[-0.1120,  0.7961, -2.6470, -0.9977, -0.3974, -0.6669],
         [ 0.5403, -0.2061,  0.5187,  0.9215,  0.8184, -1.0994],
         [ 0.5349,  0.2920,  1.7966,  0.0760,  0.0800, -1.2111],
         [-0.2927,  0.0039,  1.0246,  0.2900, -2.1198,  0.3840],
         [ 0.6989,  0.9822, -0.2448,  2.3628, -0.9668,  1.2599]],

        [[-0.7318,  1.0356,  0.3806,  0.2739, -1.1058,  0.0398],
         [ 0.9205,  1.2824, -0.8794, -1.0281,  1.2370,  1.3666],
         [ 1.1086,  1.5023,  0.3930,  0.6388, -1.1563,  0.6677],
         [ 0.3404, -0.4609, -0.2193,  0.7982,  0.3244,  1.0617],
         [ 1.1146,  1.7182,  0.1658, -1.0228,  1.2579,  1.2837]]])

In [3]:
image.shape

torch.Size([3, 5, 6])

In [4]:
print(image.mean(-3))   
print(image.mean(-3).shape)

tensor([[-0.0624,  0.5771, -0.4577, -0.5299, -1.1640, -0.0752],
        [-0.1710, -0.1120, -0.3313, -0.7373,  1.3464,  0.4671],
        [ 0.2707,  0.3191,  0.6842,  0.4858, -0.3831, -0.1551],
        [-0.0492, -0.1889,  0.4425,  0.8696, -1.1015,  0.3025],
        [ 0.6189,  1.0628,  0.1770,  0.8605,  0.4809,  0.7670]])
torch.Size([5, 6])


In [5]:
print(image.mean(-2)) # 각 행값들의 평균을 구해서 넣어준다(세로 연산)
print(image.mean(-2).shape)

tensor([[-0.4602, -0.3943,  0.2510,  0.1067, -0.0872,  0.1665],
        [ 0.2739,  0.3736,  0.0896,  0.5305, -0.5171, -0.2667],
        [ 0.5505,  1.0155, -0.0319, -0.0680,  0.1114,  0.8839]])
torch.Size([3, 6])


In [6]:
print(image.mean(-1)) # 각 열값들의 평균을 구해서 넣어준다 (가로 연산)
print(image.mean(-1).shape)

tensor([[-0.1673, -0.5012, -0.1764, -0.0516,  0.5485],
        [-0.6708,  0.2489,  0.2614, -0.1184,  0.6820],
        [-0.0179,  0.4832,  0.5257,  0.3074,  0.7529]])
torch.Size([3, 5])


In [20]:
weights = torch.tensor([[1],[1],[1]]).unsqueeze(-1) # 가장 오른쪽차원 추가 [3,1] -> [3,1,1]
print(weights)
weights.shape 

tensor([[[1]],

        [[1]],

        [[1]]])


torch.Size([3, 1, 1])

In [8]:
image * weights # [3,1,1] * [3,5,6] / [3,5,6] * [3,5,6]은 가능하나 / [3,2,1] * [3,5,6]은 연산이 불가능하다

tensor([[[ 5.7833e-01,  2.7625e-01,  1.8477e+00,  1.6780e+00, -1.2982e-01,
           6.3216e-01],
         [ 3.9858e-01, -3.8918e-01,  8.1343e-01,  6.7158e-01, -4.1242e-01,
          -2.8699e-01],
         [-8.8036e-01, -2.9735e-01,  5.3853e-02, -1.3739e+00,  6.7856e-01,
           3.0225e-01],
         [-5.9437e-01,  6.2562e-01,  2.9757e-01,  2.4109e-01,  1.4217e+00,
           1.2525e-02],
         [-1.3218e+00, -8.4334e-01,  1.7185e+00,  3.2919e-01, -7.1972e-01,
          -4.4764e-01]],

        [[ 1.6842e-01, -1.6902e+00, -1.3217e-01,  9.0236e-01,  8.5405e-01,
           1.6585e+00],
         [ 1.0030e+00, -1.8466e-01, -1.3355e+00,  3.4179e-01, -1.2985e-01,
           1.4332e+00],
         [-1.5220e-01,  1.3967e+00,  6.7098e-01,  6.4261e-01,  2.9226e-01,
           3.3068e-01],
         [ 1.8295e-03, -1.0449e+00, -4.0328e-01, -2.1275e+00,  1.4109e+00,
           2.8605e-01],
         [-2.8711e-01, -1.9110e+00,  5.6878e-01,  4.7600e-01, -1.1532e+00,
          -7.4790e-01]],

      

In [32]:
# 차원 이름 지정하기
img_names = torch.tensor([0.1, 0.2, 0.5], names=['channels'])  # 채널 이름 지정
print("원본 텐서 이름:", img_names.names)

# 텐서 이름 수정
re_img_names = img_names.rename(channels='rows')  # 올바른 차원 이름을 사용하여 수정
print("수정된 텐서 이름:", re_img_names.names)

원본 텐서 이름: ('channels',)
수정된 텐서 이름: ('rows',)


In [37]:
img_t = torch.randn(3, 5, 5) 
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
img_named.names , img_named.shape

(('channels', 'rows', 'columns'), torch.Size([3, 5, 5]))

In [49]:
# 형태 변경 
a = torch.ones(3,2)
a_t = a.transpose(0,1)
a , a.shape , a_t, a_t.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 torch.Size([3, 2]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [55]:
# 변환
a = torch.ones(3,2)
a.zero_() # 입력된 모든 텐서의 요스를 0으로 바꿈
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [53]:
## 저장 공간 확인 
points = torch.tensor([[4,5],[3,4],[2,1]])
points.storage() # 저장이 어떻게 되는지 확인 (실제로는 크기가6인 배열공간) = 차원에 무관하게 실제 저장 공간 레이아웃은 1차원

 4
 5
 3
 4
 2
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [10]:
points = torch.tensor([[4,5],[3,4],[2,1]])
points

tensor([[4, 5],
        [3, 4],
        [2, 1]])

In [62]:
# 복제 방법
points = torch.tensor([[4,5],[3,4],[2,1]])
second_point = points[1].clone() # 복제 (새로운 메모리 공간에 저장=원본 텐서에 영향을 미치지 않음 )
second_point[0] = 10
points

# 복제 x(동일한 저장공간을 가리킴)
points2 = torch.tensor([[4,5],[3,4],[2,1]])
second_point2 = points2[1]
second_point2[0] = 10

points , points2

(tensor([[4, 5],
         [3, 4],
         [2, 1]]),
 tensor([[ 4,  5],
         [10,  4],
         [ 2,  1]]))

In [20]:
# 전치 연산 
some_t = torch.ones(3,4,5)
transpost_t = some_t.transpose(0,2)  # 0차원과 2차원 위치를 변경시킨다 
transpost_t.shape , transpost_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [21]:
transpost_t.is_contiguous() 

False

In [22]:
transpost_t = transpost_t.contiguous() # 인접한 텐서로 만들어줌(가끔 인접한 텐서에 대해서만 동작하는 경우가 있음 , 메모리에 연속적으로 저장되어 있는 경우)
transpost_t.is_contiguous() 

True

In [72]:
## numpy배열로 변환
t = torch.ones(3,4)
t_np = t.numpy()
t_torch = torch.from_numpy(t_np)

In [86]:
# 연습문제
a = torch.tensor(list(range(9)))
a = a.view(3,3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
''' 참고로 view vs reshape 
view : 텐서의 모양반 변경 , 데이터는 변경x / 기존 텐서와 동일한 메모리 공간 사용 / 총 요소수가 변경x
reshape : 텐서의 모양과 데이터를 모두 변경 /  새로운 메모리 공간 할당 / 총 요소수가 변해도 된다.

속도는 view가 훨신 빠름 
'''

In [88]:
b = a[1:,1:]
b

tensor([[4, 5],
        [7, 8]])