In [1]:
import torch
import matplotlib.pyplot as plt
a = torch.ones(3) # 크기가 3인 1차원 텐서
print(a)
print(a.shape)

tensor([1., 1., 1.])
torch.Size([3])


In [9]:
points = torch.tensor([[4.0, 1.0 ,3], [5.0, 3.0,3], [2.0, 1.0,3]])
print(points)
print(points.shape) 
print(points[0,1])                                                                                                                         

tensor([[4., 1., 3.],
        [5., 3., 3.],
        [2., 1., 3.]])
torch.Size([3, 3])
tensor(1.)


In [10]:
image = torch.randn(3,5,6) # 3채널(색) , 5행 , 6열
image

tensor([[[-1.6958e+00,  2.3777e-01,  3.8842e-01,  2.7796e-01,  2.2868e-01,
          -2.6154e-01],
         [ 7.0473e-01,  1.1601e+00,  8.0190e-02, -4.0737e-01,  4.7210e-01,
           8.3322e-01],
         [ 6.5348e-01,  6.7286e-01,  7.2607e-01, -4.2413e-01, -5.4338e-01,
           4.2493e-01],
         [-2.5316e-01,  3.6846e-01, -9.2816e-01,  3.5734e-02, -9.9915e-01,
           7.5915e-01],
         [-1.5289e-01, -1.7803e-01, -2.6959e-01,  1.1033e+00, -5.2463e-01,
          -5.4542e-01]],

        [[ 1.1953e+00,  1.9227e+00,  1.6895e+00, -2.3116e-01, -3.7591e-04,
           6.9854e-01],
         [ 1.9997e+00, -3.6545e-01,  1.5327e+00, -3.6427e-01, -3.5198e-01,
           1.6524e+00],
         [ 9.7517e-02, -2.9272e-01, -3.0911e-01, -2.9190e-01, -4.2896e-01,
           6.2179e-01],
         [-2.5018e+00, -1.2892e+00,  1.1763e-01, -7.3423e-01,  8.8597e-01,
           2.6264e-01],
         [ 4.6836e-01,  4.2559e-01,  7.2875e-03, -3.1958e-02,  1.7152e+00,
          -1.9976e+00]],

      

In [13]:
image.shape

torch.Size([3, 5, 6])

In [17]:
print(image.mean(-3)) # 채널에 관해서 평균 구함 (1,1)값 평균 = 0.0039 , (1,2)값 평균 = -0.1465  
print(image.mean(-3).shape)

tensor([[-0.0328,  1.1338,  1.0469,  0.0598, -0.0692,  0.7064],
        [ 1.0993,  0.3685,  0.4520, -0.4052,  0.5543,  1.1375],
        [-0.4072, -0.0396,  0.2930, -0.5343, -0.3526, -0.2065],
        [-1.1120, -0.4597, -0.3586, -0.5729, -0.0303,  0.8546],
        [ 0.1059,  0.2198, -0.1642,  0.2197,  0.7746, -0.8486]])
torch.Size([5, 6])


In [16]:
print(image.mean(-2)) # 각 행값들의 평균을 구해서 넣어준다(세로 연산)
print(image.mean(-2).shape)

tensor([[-0.1487,  0.4522, -0.0006,  0.1171, -0.2733,  0.2421],
        [ 0.2518,  0.0802,  0.6076, -0.3307,  0.3640,  0.2476],
        [-0.3111,  0.2013,  0.1545, -0.5261,  0.4354,  0.4964]])
torch.Size([3, 6])


In [15]:
print(image.mean(-1)) # 각 열값들의 평균을 구해서 넣어준다 (가로 연산)
print(image.mean(-1).shape)

tensor([[-0.1374,  0.4738,  0.2516, -0.1695, -0.0945],
        [ 0.8791,  0.6839, -0.1006, -0.5432,  0.0978],
        [ 0.6808,  0.4455, -0.7747, -0.1267,  0.1503]])
torch.Size([3, 5])


In [20]:
weights = torch.tensor([[1],[1],[1]]).unsqueeze(-1) # 가장 오른쪽차원 추가 [3,1] -> [3,1,1]
print(weights)
weights.shape 

tensor([[[1]],

        [[1]],

        [[1]]])


torch.Size([3, 1, 1])

In [8]:
image * weights # [3,1,1] * [3,5,6] / [3,5,6] * [3,5,6]은 가능하나 / [3,2,1] * [3,5,6]은 연산이 불가능하다

tensor([[[ 5.7833e-01,  2.7625e-01,  1.8477e+00,  1.6780e+00, -1.2982e-01,
           6.3216e-01],
         [ 3.9858e-01, -3.8918e-01,  8.1343e-01,  6.7158e-01, -4.1242e-01,
          -2.8699e-01],
         [-8.8036e-01, -2.9735e-01,  5.3853e-02, -1.3739e+00,  6.7856e-01,
           3.0225e-01],
         [-5.9437e-01,  6.2562e-01,  2.9757e-01,  2.4109e-01,  1.4217e+00,
           1.2525e-02],
         [-1.3218e+00, -8.4334e-01,  1.7185e+00,  3.2919e-01, -7.1972e-01,
          -4.4764e-01]],

        [[ 1.6842e-01, -1.6902e+00, -1.3217e-01,  9.0236e-01,  8.5405e-01,
           1.6585e+00],
         [ 1.0030e+00, -1.8466e-01, -1.3355e+00,  3.4179e-01, -1.2985e-01,
           1.4332e+00],
         [-1.5220e-01,  1.3967e+00,  6.7098e-01,  6.4261e-01,  2.9226e-01,
           3.3068e-01],
         [ 1.8295e-03, -1.0449e+00, -4.0328e-01, -2.1275e+00,  1.4109e+00,
           2.8605e-01],
         [-2.8711e-01, -1.9110e+00,  5.6878e-01,  4.7600e-01, -1.1532e+00,
          -7.4790e-01]],

      

In [32]:
# 차원 이름 지정하기
img_names = torch.tensor([0.1, 0.2, 0.5], names=['channels'])  # 채널 이름 지정
print("원본 텐서 이름:", img_names.names)

# 텐서 이름 수정
re_img_names = img_names.rename(channels='rows')  # 올바른 차원 이름을 사용하여 수정
print("수정된 텐서 이름:", re_img_names.names)

원본 텐서 이름: ('channels',)
수정된 텐서 이름: ('rows',)


In [37]:
img_t = torch.randn(3, 5, 5) 
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
img_named.names , img_named.shape

(('channels', 'rows', 'columns'), torch.Size([3, 5, 5]))

In [49]:
# 형태 변경 
a = torch.ones(3,2)
a_t = a.transpose(0,1)
a , a.shape , a_t, a_t.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 torch.Size([3, 2]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [55]:
# 변환
a = torch.ones(3,2)
a.zero_() # 입력된 모든 텐서의 요스를 0으로 바꿈
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [53]:
## 저장 공간 확인 
points = torch.tensor([[4,5],[3,4],[2,1]])
points.storage() # 저장이 어떻게 되는지 확인 (실제로는 크기가6인 배열공간) = 차원에 무관하게 실제 저장 공간 레이아웃은 1차원

 4
 5
 3
 4
 2
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [62]:
# 복제 방법
points = torch.tensor([[4,5],[3,4],[2,1]])
second_point = points[1].clone() # 복제 
second_point[0] = 10
points

# 복제 x(동일한 저장공간을 가리킴)
points2 = torch.tensor([[4,5],[3,4],[2,1]])
second_point2 = points2[1]
second_point2[0] = 10

points , points2

(tensor([[4, 5],
         [3, 4],
         [2, 1]]),
 tensor([[ 4,  5],
         [10,  4],
         [ 2,  1]]))

In [66]:
# 전치 연산 
some_t = torch.ones(3,4,5)
transpost_t = some_t.transpose(0,2)  # 0차원과 2차원 위치를 변경시킨다 
transpost_t.shape , transpost_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [67]:
some_t.contiguous() # 인접한 텐서로 만들어줌(가끔 인접한 텐서에 대해서만 동작하는 경우가 있음 )

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [72]:
## numpy배열로 변환
t = torch.ones(3,4)
t_np = t.numpy()
t_torch = torch.from_numpy(t_np)

In [86]:
# 연습문제
a = torch.tensor(list(range(9)))
a = a.view(3,3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [88]:
b = a[1:,1:]
b

tensor([[4, 5],
        [7, 8]])