In [1]:
import numpy as np
import torch
wine_path = "./winedata.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
winet = torch.from_numpy(wineq_numpy)
data = winet[:,:-1]
target = winet[:,-1]
data , data.shape , target

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]),
 tensor([6., 6., 6.,  ..., 6., 7., 6.]))

In [18]:
data.mean(-1)

tensor([23.3296, 15.3521, 14.3205,  ..., 14.8194, 14.0655, 13.0709])

In [14]:
data_mean = torch.mean(data,dim=0) 
data_var = torch.var(data,dim=0) # 각 열의 평균 , 표준편차
data_normalized = (data-data_mean) / torch.sqrt(data_var)
data_normalized , data_normalized.shape # 표준화
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [12]:
bad_indexes = target <=3
bad_indexes

tensor([False, False, False,  ..., False, False, False])

In [16]:
big_data = data[target <=3] # target이 3보다 적은것들 
big_data.shape # 총 20개 

torch.Size([20, 11])