In [10]:
import numpy as np
import torch
wine_path = "./winedata.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
winet = torch.from_numpy(wineq_numpy)
data = winet[:,:-1]
target = winet[:,-1]
data , data.shape , target

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]),
 tensor([6., 6., 6.,  ..., 6., 7., 6.]))

In [9]:
data_mean = torch.mean(data,dim=0) 
data_var = torch.var(data,dim=0) # 각 열의 평균 , 표준편차
data_normalized = (data-data_mean) / torch.sqrt(data_var)
data_normalized , data_normalized.shape # 표준화

(tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
          -3.4915e-01, -1.3930e+00],
         [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
           1.3422e-03, -8.2419e-01],
         [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
          -4.3677e-01, -3.3663e-01],
         ...,
         [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
          -2.6153e-01, -9.0545e-01],
         [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
          -9.6251e-01,  1.8574e+00],
         [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
          -1.4882e+00,  1.0448e+00]]),
 torch.Size([4898, 11]))

In [12]:
bad_indexes = target <=3
bad_indexes

tensor([False, False, False,  ..., False, False, False])

In [16]:
big_data = data[target <=3] # target이 3보다 적은것들 
big_data.shape # 총 20개 

torch.Size([20, 11])