## 원핫 인코딩 하기

In [19]:
import numpy as np
import torch
wine_path = "./winedata.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
winet = torch.from_numpy(wineq_numpy)
winet.shape


torch.Size([4898, 12])

In [33]:
target = winet[:,-1].long() # 레이블이 정수로 할당
target , target.shape

(tensor([6, 6, 6,  ..., 6, 7, 6]), torch.Size([4898]))

In [34]:
target.unsqueeze(1).shape

torch.Size([4898, 1])

In [37]:
target_onehot = torch.zeros(target.shape[0],10)
target_onehot, target_onehot.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

In [36]:
target_onehot.scatter_(1,target.unsqueeze(1),1.0) # 대상 레이블에 해당하는 열에 1.0을 받게 된다 . (산포가수행되는차원,인덱스,넣을값)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

## tensor stride 개념 정확히 (bike데이터셋 활용)

In [41]:
bikes_numpy = np.loadtxt("./hour-fixed.csv",
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])}) # <1>
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

In [42]:
view_bike = bikes.view(-1,24,bikes.shape[1])
view_bike.shape , view_bike.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [ ]:
view_bike.storage()

In [43]:
view_bike_t = view_bike.transpose(1, 2)
view_bike_t.shape, view_bike_t.stride() # 새로 저장소를 할당할 필요가 없이 계산이 편하다

(torch.Size([730, 17, 24]), (408, 1, 17))